blank_issues_enabled: false
contact_links:
  - name: 🧬 ONT Customer Support
    url: https://nanoporetech.com/support/customer-support
    about: Please use the ONT customer support for help with sequencing, library preparation and analysis.
