OPTION(BUILD_KOI_FROM_SOURCE OFF)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux" OR WIN32)

    if(BUILD_KOI_FROM_SOURCE)
        message(STATUS "Building Koi from source")

        set(KOI_DIR "${DORADO_3RD_PARTY}/koi")
	
        if(NOT EXISTS ${KOI_DIR})
            if(DEFINED GITLAB_CI_TOKEN)
                message("Cloning Koi using CI token")
                execute_process(COMMAND git clone https://gitlab-ci-token:${GITLAB_CI_TOKEN}@git.oxfordnanolabs.local/machine-learning/koi.git ${KOI_DIR})
            else()
                message("Cloning Koi using ssh")
                execute_process(COMMAND git clone git@git.oxfordnanolabs.local:machine-learning/koi.git ${KOI_DIR})
            endif()
            execute_process(COMMAND git checkout d4418e42334492d9b13f9c33d40ede136021c430 WORKING_DIRECTORY ${KOI_DIR})
        endif()
        add_subdirectory(${KOI_DIR}/koi/lib)

	set(KOI_INCLUDE ${KOI_DIR}/koi/lib)
	set(KOI_LIBRARIES koi)
    else()
        message(STATUS "Using prebuilt Koi from ${KOI_DIR}")
	if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
            download_and_extract(https://nanoporetech.box.com/shared/static/iwciavd9vfzff63korwn0pcdxsmom0wd.gz koi_lib)
            file(GLOB KOI_DIR "${DORADO_3RD_PARTY}/koi_lib/*")
	    set(KOI_LIBRARIES ${KOI_DIR}/lib/libkoi.a)
        elseif(WIN32)
            download_and_extract(https://nanoporetech.box.com/shared/static/8ad81xuqdrkrwepey6pdis795bvlvi7r.zip koi_lib)
            file(GLOB KOI_DIR "${DORADO_3RD_PARTY}/koi_lib/*")
	    set(KOI_LIBRARIES ${KOI_DIR}/lib/koi.lib)
        endif()
	set(KOI_INCLUDE ${KOI_DIR}/include)
    endif()
endif()
